version: "3"
services: 
  nginx:
    image: nginx:latest
    container_name: "nginx-node-1"
    depends_on:
      - egg-code-audition
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/www/cert/cert.pem:/www/cert/cert.pem"
      - "/www/cert/cert.key:/www/cert/cert.key"
      - "/www/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    links:
      - "egg-code-audition:egg-code-node-1"
    networks:
     - code-audition-network
  mongo:
    image: mongo:latest
    container_name: "mongo-node-1"
    ports:
      - "27017:27017"
    volumes:
      - "/www/data/mongo:/data/db"
    networks:
      - code-audition-network
  redis: 
    image: redis
    container_name: "redis-node-1"
    ports:
      - "6379:6379"
    volumes:
      - "/www/data/redis:/data"
      - "/www/data/redis-conf/redis.conf:/etc/redis/redis.conf"
    networks:
      - code-audition-network
    command: redis-server /etc/redis/redis.conf

  egg-code-audition:
    build: .
    container_name: "egg-code-node-1"
    ports: 
      - "7001:7001"
    depends_on:
      - mongo
    volumes: 
      - "/www/logs/test:/root/logs"
    links:
      - "mongo:mongo-node-1"
    networks:
     - code-audition-network
networks: 
  code-audition-network:
    driver: bridge